version: 2.1

jobs:
  build:
    docker:
      - image: cimg/elixir:1.15.5-erlang-26.0.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            mix local.hex --force && \
            mix local.rebar --force
      - restore_cache:
          keys:
            - v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v2-mix-cache-{{ .Branch }}
            - v2-mix-cache
      - run:
          name: Get dependencies
          command: mix deps.get
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - restore_cache:
          keys:
            - v4-build-cache-{{ .Branch }}
            - v4-build-cache
      - run:
          name: Compile
          command: mix do deps.compile, compile --warnings-as-errors, dialyzer --plt
      - save_cache:
          key: v4-build-cache-{{ .Branch }}
          paths:
            - _build
      - persist_to_workspace:
          root: ~/
          paths:
            - .mix
            - project/_build
            - project/deps

  test:
    docker:
      - image: cimg/elixir:1.15.5-erlang-26.0.2
        environment:
          MIX_ENV: test
      - image: cimg/postgres:14.6
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: mix test --cover --export-coverage default
      - run:
          name: Check coverage
          command: mix test.coverage
      - store_test_results:
          path: /tmp/test/results.xml

  lint:
    docker:
      - image: cimg/elixir:1.15.5-erlang-26.0.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Check formatting
          command: mix format --check-formatted --dry-run
      - run:
          name: Check for retired dependencies
          command: mix hex.audit
      - run:
          name: Check unused dependencies
          command: mix deps.unlock --check-unused
      - run:
          name: Check outdated dependencies
          command: mix hex.outdated --within-requirements || true
      - run:
          name: Credo
          command: mix credo --all
      - run:
          name: Dialyzer
          command: mix dialyzer
      - run:
          name: Check documentation
          command: mix doctor

  security:
    docker:
      - image: cimg/elixir:1.15.5-erlang-26.0.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Audit dependencies
          command: mix deps.audit
      - run:
          name: Sobelow
          command: mix sobelow --config

  slscan:
    docker:
      - image: shiftleft/sast-scan:maven385
    environment:
      FETCH_LICENSE: "true"
    working_directory: /tmp/shiftleft-scan
    steps:
      - checkout
      - run:
          name: Scan
          command: scan --no-error
      - store_artifacts:
          path: reports
          destination: sast-scan-reports

workflows:
  test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - security:
          requires:
            - build
      - slscan:
          filters:
            branches:
              only:
                - master
